# Generated by Django 2.2.2 on 2019-06-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverb',
            name='lvl',
            field=models.SmallIntegerField(choices=[(1, 'Intensifier'), (2, 'Booster'), (3, 'Diminisher'), (4, 'Minimizer'), (5, 'Modifier')], verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='adverb',
            name='txt',
            field=models.CharField(max_length=100, unique=True, verbose_name='Text'),
        ),
    ]
