# Generated by Django 2.2.2 on 2019-06-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_auto_20190610_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.CharField(max_length=100, unique=True, verbose_name='Text')),
                ('score', models.FloatField(verbose_name='Score')),
                ('sentiment', models.SlugField(choices=[(1, 'Negative'), (2, 'Positive')], verbose_name='Sentiment')),
            ],
        ),
    ]
